services:
  - type: web
    name: benaa-ai-assistant
    env: python
    plan: free  # يمكنك تغييره إلى professional إذا كنت تستخدم خطة مدفوعة
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_key_here
      - key: ANTHROPIC_API_KEY
        value: your_anthropic_key_here
      - key: DEEPSEEK_API_KEY
        value: your_deepseek_key_here
      - key: GEMINI_API_KEY
        value: your_gemini_key_here
    autoDeploy: true
